name: pub
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  universal_html: ^1.2.3
  meta: ^1.2.2
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  effective_dart: ^1.2.4
  test_coverage: ^0.4.2