name: CI-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.2
    - name: Install Dependencies
      run: pub get
    - name: Run Tests
      run: pub run test
    - name: Code Coverage
      run: pub run test_coverage
    - name: Code Coverage -> Check
      uses: ChicagoFlutter/lcov-cop@v1.0.0
    - name: Code Coverage -> Upload
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
